services:
  - type: web
    name: luna-disparo
    runtime: node
    rootDirectory: frontend/disparo
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: LUNA_API_URL
        value: https://eclipse-bursa-evolution-declare.trycloudflare.com
